[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
dependencies = [
    "docxtpl",
    "pywin32",
    "xlrd",
    "openpyxl",
    "docx2pdf",
    "pysimplegui",
    "python-dotenv",
]