[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[project]
dependencies = [
    "docxtpl>=0.16.7",
    "pywin32",
    "xlrd>=2.0.1",
    "openpyxl>=3.1.2",
    "docx2pdf>=0.1.8",
    "pysimplegui>=4.53.0",
    "python-dotenv",
]